# Generated by Django 6.0.1 on 2026-01-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passender',
            new_name='Passenger',
        ),
    ]
